### PR TITLE
Adding support for shader includes pre-processor directives

### PR DESCRIPTION
**Pull request by adriengivry**
# Description
Added support for shader includes, which allow us to reuse code between shaders:

The `Overload/Resources/` folder has been added to premake as a separate project, so this way we can see and edit resources (such as engine and editor shaders) directly from VS (or any other IDE of your choice).

# Review Guidance
Now passing an optional `path` to `realPath` conversion function to the `ShaderLoader` class, to be able to parse and load included files based on rules set by the caller (`OvCore`). This way `OvRendering` doesn't have to be aware of our folder architecture.
If a file starting with `:` is included, ie:
```c
#include ":Shaders/Vertex/Basic.ovfxh"
```
The `ShaderLoader` will resolve the file path and look into the Engine folder.
If no `:` is provided, it will look into the user project's assets, ie:
```c
#include "Shaders/MyCustomShader.ovfxh"
```

Some conventions have been introduced:
- Shader files are named `*.ovfx`
- Partial shader files (included) are named `*.ovfxh`

# Example

```glsl
// Unlit.ovfx

#shader vertex
#version 430 core

#include ":Shaders/Common/Buffers/EngineUBO.ovfxh"
#include ":Shaders/Common/Utils.ovfxh"

layout (location = 0) in vec3 geo_Pos;
layout (location = 1) in vec2 geo_TexCoords;

out VS_OUT
{
    vec3 FragPos;
    vec2 TexCoords;
} vs_out;

void main()
{
    vs_out.FragPos = vec3(ubo_Model * vec4(geo_Pos, 1.0));
    vs_out.TexCoords = geo_TexCoords;

    gl_Position = ubo_Projection * ubo_View * vec4(vs_out.FragPos, 1.0);
}

#shader fragment
#version 430 core

#include ":Shaders/Common/Buffers/EngineUBO.ovfxh"
#include ":Shaders/Common/Utils.ovfxh"

in VS_OUT
{
    vec3 FragPos;
    vec2 TexCoords;
} fs_in;

uniform vec4 u_Diffuse = vec4(1.0);
uniform sampler2D u_DiffuseMap;
uniform vec2 u_TextureTiling = vec2(1.0);
uniform vec2 u_TextureOffset = vec2(0.0);

out vec4 FRAGMENT_COLOR;

void main()
{
    vec2 texCoords = TileAndOffsetTexCoords(fs_in.TexCoords, u_TextureTiling, u_TextureOffset);
    FRAGMENT_COLOR = texture(u_DiffuseMap, texCoords) * u_Diffuse;
}
```

# Limitations
The current implementation doesn't support including the same shader file multiple time, and doing so will potentially result into compilation errors.

# Screenshots
image
_Addition of the "Resources" project (SharedItems)_

# Related Issues
Fixes https://github.com/adriengivry/Overload/issues/104

### CODE REVIEW

**Comment by adriengivry** [comment]
Rebased the PR following the merge of https://github.com/adriengivry/Overload/pull/277

**Comment by adriengivry** [comment]
@maxbrundev @litelawliet I might need some help on this one to define the default extension for partial shader files (shader files that are included, but cannot be compiled by themselves).

**Comment by adriengivry** [comment]
@litelawliet @maxbrundev I went with `.ovfx` and `.ovfxh` for now. I've also improved standard shader code to be more consistent and easier to work with when creating new shaders.

I've found one current limitation with this implementation, which might need further work (maybe in another PR?).

I'm also considering using `#pragma` statements instead of `#shader [vertex/fragment]`, as it's better handled by most IDEs when it comes to syntax highlighting, and might be more standard.

**Review by litelawliet — APPROVED** [review]

**Comment by adriengivry** [comment]
Related documentation:
https://github.com/adriengivry/Overload/wiki/Custom-Shaders

**Pull request merged**
