### PR TITLE
Fixing HardwareInfo panel memory leak

### PR DESCRIPTION
**Pull request by maxbrundev**
Fixing issue #278

### CODE REVIEW

**Comment by adriengivry** [comment]
I just realized that the memory management of our UI elements is not super great. I can see that we never remove widgets properly. To be honest we should never have to remove widgets manually in the destructor, but instead memory should be freed by the `WidgetContainer` on destruction (for widget with internally managed memory).

I would suggest that instead of going over all our panels and calling `RemoveAllWdigets` manually, we should update the `WidgetContainer` to properly de-allocate memory using RAII.

**Review by adriengivry — COMMENTED** [review]
I'd suggest looking to solve `OvUI` de-allocation issues instead of addressing de-allocation for each panel manually

**Comment by maxbrundev** [comment]
> I just realized that the memory management of our UI elements is not super great. I can see that we never remove widgets properly. To be honest we should never have to remove widgets manually in the destructor, but instead memory should be freed by the `WidgetContainer` on destruction (for widget with internally managed memory).
> 
> I would suggest that instead of going over all our panels and calling `RemoveAllWdigets` manually, we should update the `WidgetContainer` to properly de-allocate memory using RAII.

Indeed! I updated the WidgetContainer with shared_ptr due to the possibility to consider not owned AWidget instances

**Review by adriengivry — COMMENTED** [review]
Your removal of the `p_manageMemory` option (which allow for external memory management of widgets) got me thinking if we ever really needed it.

There is one use case in the `FPSCounter`, which is unconventional, as the widget is allocated on the stack (because it's in the `FPSCounter` class member definition), and the reason we did that was because we wanted to make it available to the `Update` method.

If instead we used `CreateWidget` to create the `FPSCounter.m_text`, we could store the widget as an optional reference (`std::optional<std::reference_wrapper<TextColored>>`), which would completely remove our only use case for this feature.

Not sure your latest change fully support the external memory management case (actually I double checked and it doesn't, casting a stack allocated member variable to a `shared_ptr` won't have the behaviour we might expect), so we'd better fully remove the only use case we have (`FPSCounter`).

On another note, I would advise against using `shared_ptr` here, as you don't need to share the memory ownership. The ownership and responsibility should only be handled by the `WidgetContainer`, so `unique_ptr` would make more sense here.

**Review by adriengivry — APPROVED** [review]
LGTM!

**Comment by maxbrundev** [comment]
Opening issue #281 in order to address the memory management rework of the Widgets in an another dedicated PR

Merging this PR in order to provide a quick fix for the memory leaks occurring from the `WidgetContainer ` usage

**Pull request merged**
